apiVersion: v1
kind: Service
metadata:
  name: platform-postgres
  namespace: database
spec:
  type: ClusterIP
  selector:
    app: platform-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
