apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    aws_access_key_id: bf5726cd1ed3f9b33eac7abd
    aws_secret_access_key: VRWpPpfIjKTCxoukii0Va1foX7lOSxMqkb/axaNU5hA=
    endpoint: http://minio.minio.svc.cluster.local:9000
    path_style: true
