apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.gitlab.io
      chart: gitlab
      targetRevision: 10.0.1
      helm:
        valueFiles:
          - $values/platform/gitlab/values.yaml
    - repoURL: https://github.com/Hamzefaourii/devops-platform-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
