mode: standalone

rootUser: "bf5726cd1ed3f9b33eac7abd"
rootPassword: "VRWpPpfIjKTCxoukii0Va1foX7lOSxMqkb/axaNU5hA="

persistence:
  enabled: true
  storageClass: hcloud-volumes
  size: 20Gi
  accessMode: ReadWriteOnce

service:
  type: ClusterIP
  port: "9000"

consoleService:
  type: ClusterIP
  port: "9001"

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  hosts:
    - minio.local

consoleIngress:
  enabled: true
  ingressClassName: nginx
  path: /
  hosts:
    - minio-console.local

resources:
  requests:
    memory: 256Mi
    cpu: 100m
